services:
  postgres:
    image: postgres:16
    container_name: shopease_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-shopease}
    ports:
      - "5432:5432"
    volumes:
      - ./api/postgres/init:/docker-entrypoint-initdb.d
      - ./api/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-shopease}",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - shopease-network

  mongo:
    image: mongo:7
    container_name: shopease_mongo
    command: --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./api/mongo/init:/docker-entrypoint-initdb.d
      - ./api/mongo/data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - shopease-network

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: shopease_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_REQUEST_TIMEOUT: 300
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - shopease-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: shopease_mongo_express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    networks:
      - shopease-network
    restart: unless-stopped

  api:
    build:
      context: ./api/fastApi
      dockerfile: Dockerfile
    container_name: shopease_api
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-shopease}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=shopease
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./api/fastApi/app:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - shopease-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: runner # Production optimisée (multi-stage)
    container_name: shopease_frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - API_URL=http://api:8000
      - HOSTNAME=0.0.0.0
      - PORT=3000
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - api
    networks:
      - shopease-network
    restart: unless-stopped

networks:
  shopease-network:
    driver: bridge
    name: shopease-network

volumes:
  pgadmin-data:
    name: shopease_pgadmin_data
